#docker-compose -f docker-compose-prod.yml up -d
version: "3"
services:
  api:
    build: .
    ports:
      - 80:8000
    # env_file:
    #     - ./.env
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    expose:
      - ${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
volumes:
  postgres_data:
